project:
  type: website
  output-dir: docs


execute:
  freeze: true

website:
  title: "STRATOS TG2: Selection of variables and functional forms for multivariable models"
  site-url: https://stratostg2.github.io/
  description: "Add description"
  page-navigation: false

  sidebar:
    style: "docked"
    background: light
    search: true
    collapse-level: 2
    tools:
      - icon: github
        href: https://github.com/stratostg2/
    contents:
      - index.qmd
      - members.qmd
      - papers.qmd
      - activities.qmd
      - resources.qmd
      - glossary.qmd
      - about.qmd
    logo: "assets/stratos-color-transpbackgr.png"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

