---
title: "Activities"
---

## Upcoming

* Invited talk at the [CFE-CMStatistics 2025](https://www.cmstatistics.org/CFECMStatistics2025) (19th International Joint Conference on Computational and Financial Econometrics and Computational and Methodological Statistics) in London, UK, 13-15 Dec 2025. 
Topic of the session: Researcher degrees of freedom, flexible modeling and interpretability. 
Speaker: Theresa Ullmann. 
Topic of the talk: Comparing methods for flexible estimation of non-linear associations: The importance of suitable performance measures (project TG2-P8). 

## Recent

* Invited session at the [ROeS 2025](https://roes2025.at/index.html) (Conference of the Austro-Swiss Region of the International Biometric Society) in Graz, A, 14-18 Sep 2025. Topic of the session: Contrasting Bayesian and frequentist model building for descriptive research questions - a paired-design experiment of STRATOS-TG2. 
Invited speaker: <a href="/assets/Mariana_slides_Roes_2025.pdf" target="_blank" rel="noopener noreferrer">Mariana Nold</a>. 
Further speakers for TG2: <a href="/assets/20250902_Kammer.pdf" target="_blank" rel="noopener noreferrer">Michael Kammer</a>, 
<a href="/assets/Aliaksandr_slides_Roes_2025.pdf" target="_blank" rel="noopener noreferrer">Aliaksandr Hubin</a>, 
<a href="/assets/2025-09 Roes Heinze.pdf" target="_blank" rel="noopener noreferrer">Georg Heinze</a>.

<details>
  <summary>Session abstract and pictures</summary>

### Abstract 

Statistical inference is characterized by a rich epistemological diversity, underpinned by both historical and contemporary debates. The frequentist approach, never having been a closed theory, was characterized by conflicts within statistical methodologies. Similarly, significant differences and even conflicts have existed both within and between frequentist and Bayesian schools.
Despite these tensions, efforts have been made to combine the strengths of frequentist and Bayesian approaches in a pragmatic manner, rather than adhering dogmatically to one paradigm. Our session aims to explore the extent to which modelling approaches are inherently frequentist or Bayesian, and whether these distinctions lead to divergent results. We will compare Bayesian and frequentist model building in four case studies: predicting bacteremia, estimating the proportion of body fat, describing the orbits of exoplanets, investigating the sense of school-belonging in Austrian pupils. For each case study, a research question suited to a multivariable regression model was defined. Two analysis plans were developed per study by different individuals: one Bayesian and one frequentist. Data is currently being analyzed in parallel, and results will be presented in the session. We will thoroughly discuss each step, examining the nuances of each approach to enhance understanding of the methodological and practical implications of statistical inference paradigms in complex, real-world problems.

Pictures: 

[Starting the session](/assets/1758101359311.jpeg) (thanks to Sereina Herzog)

[After the session](/assets/PXL_20250918_080447284.jpg) (thanks to Alexandra Kaider)

</details>



* Invited talk at the [ROeS 2025](https://roes2025.at/index.html) (Conference of the Austro-Swiss Region of the International Biometric Society) in Graz, A, 14-18 Sep 2025. Topic of the session: Towards best practices in medical statistics: The need to implement innovative scientific solutions. Speaker: Theresa Ullmann. Topic of the talk: [Neutral Comparisons Of Statistical Methods: Opportunities, Challenges, And Common Issues](assets/Slides ROeS Ullmann.pdf) (Includes as an example TG2-P11, Simulation study on variable selection)


* Invited session at 70th Annual Meeting of the German Society for Medical Informatics, Biometrics and Epidemiology (Deutsche Gesellschaft für Medizinische Informatik, Biometrie und Epidemiologie e. V., GMDS) in Jena, Germany, 7-11 Sep 2025. Speaker for TG2: Gregor Buch. Topic of the talk: STRATOS Topic Group 2 – Selection of variables and functional forms in multivariable analysis: Results from a review of Covid-19 prognostic models. [Slides](assets/Covid-Modeling-Review_Talk_GMDS2025.pdf)

* Minisymposium at the International Society of Clinical Biostatistics (ISCB) conference in Basel, CH, 28 Aug 2025. Topic of the session: Statistical Research needs to improve – on the important roles of simulation studies and guidance for analysis. Speakers (among others): Georg Heinze, Willi Sauerbrei, Michal Abrahamowicz. [Find out more](https://iscb2025.info/mini-symposia.html#mini-symposium-3-statistical-research-needs-to-improve-on-the-important-roles-of-simulation-studies-and-guidance-for-analysis)

* Topic-contributed paper session at Joint Statistical Meeting (JSM), 6 Aug 2025. Speaker for TG2: Marc Henrion. Topic of the talk: STRATOS Topic Group 2 – Selection of variables and functional forms in multivariable analysis: Results from a review of Covid-19 prognostic models.[Find out more](https://ww2.amstat.org/meetings/jsm/2025/)

* Internal TG2 meeting in Vienna, 7-9 May 2025 at the [Center for Medical Data Science](https://data-science.meduniwien.ac.at), including a public talk by Matthias Schmid on [Achieving explainable machine learning by functional decomposition of black-box models into explainable predictor effects](https://viennabiometrics.github.io/abstracts/20250805_WBS_Schmid.pdf)

* Georg Heinze and Theresa Ullmann presented a 3-hour Statistics in Practice Showcase session at the International Biometric Conference in Atlanta, GA, USA, December 2024. Find out more at [https://www.ibc2024.org](https://www.ibc2024.org/events/showcase). [The slides are available at OSF here](https://osf.io/a5gtk/).


## Upcoming


* summer activities completed! we are preparing for 2026...


