---
title: "Members"
---

**[Georg Heinze](https://www.meduniwien.ac.at/researcher/georg_heinze) (chair)**: Institute of Clinical Biometrics, Center for Medical Data Science, Medical University of Vienna,  Austria. 

**[Aris Perperoglou](https://uk.linkedin.com/in/arisperperoglou) (chair)**:  Predictive Modelling, GSK, Stevenage, UK

**[Willi Sauerbrei](https://www.uniklinik-freiburg.de/english/imbi/mitarbeiter.html?imbiuser=wfs) (chair)**: Institute for Medical Biometry and Medical Informatics, Medical Center - University of Freiburg, Germany 

**Michal Abrahamowicz**: Faculty of Medicine, McGill University, Canada

**Harald Binder**:  Institute for Medical Biometry and Medical Informatics, Medical Center - University of Freiburg, Germany 

**[Daniela Dunkler](https://www.meduniwien.ac.at/researcher/daniela_dunkler)**: Institute of Clinical Biometrics, Center for Medical Data Science, Medical University of Vienna,  Austria

**Frank Harrell**: School of Medicine, Vanderbilt University Medical Center, Nashville, TN, USA

**Marc Henrion**: Malawi Liverpool Wellcome Research Programme, Blantyre, Malawi and Department of Clinical Sciences, Liverpool School of Tropical Medicine, Liverpool, UK

**Michael Kammer**: Division of Nephrology, Department of Medicine III and Institute of Clinical Biometrics, Center for Medical Data Science, Medical University of Vienna,  Austria

**[Mariana Nold](https://www.fsv.uni-jena.de/19575/dr-mariana-nold)**: Department of Sociology, Friedrich-Schiller University of Jena, Jena, Germany

**Matthias Schmid**:  Institute for Medicine Biometry, Informatics and Epidemiology, University of Bonn, Bonn, Germany

## Clinical affiliate

**Carl-Stephan Leonhardt**: Department of Surgery, Medical University of Vienna, Vienna, Austria

## Early career adjunct members

**Gregor Buch**: Preventive Cardiology and Preventive Medicine, Department of Cardiology, University Medical Center of the Johannes Gutenberg University Mainz, Mainz, Germany

**Edwin  Kipruto**:  Institute for Medical Biometry and Medical Informatics, Medical Center - University of Freiburg, Germany

**[Theresa Ullmann](https://www.meduniwien.ac.at/researcher/theresa_ullmann)**: Institute of Clinical Biometrics, Center for Medical Data Science, Medical University of Vienna,  Austria

