---
title: "Resources"
---

## Apps

**[Bend your (sp)line](https://clinicalbiometrics.shinyapps.io/Bendyourspline/): A shiny app developed by TG2**

A shiny app to **visualize the possible different functional forms** which can be modelled with **fractional polynomials, natural (restricted cubic) splines, or linear B-splines.** For eleven different explanatory variables, you can visualise non-linear effects applying these popular methods of non-linear modeling. You can visualise first- or second-degree fractional polynomials, linear B-splines with up to 4 degrees of freedom and natural splines with up to 3 degrees of freedom.

## R packages and other resources provided by TG2 members

### Regression Modeling Strategies 

Regression modeling, testing, estimation, validation, graphics, prediction, and typesetting by storing enhanced model design attributes in the fit. 'rms' is a collection of functions that assist with and streamline modeling. 

* R package: [rms](https://cran.r-project.org/web/packages/rms/index.html) 
* Online book companion: [https://hbiostat.org/doc/rms/book/](https://hbiostat.org/doc/rms/book/) 

### Multivariable Fractional Polynomials (MFP)

MFP is a pragmatic procedure to create a multivariable model with the twin aims of selecting important variables and determining a suitable functional form for continuous predictors. 

Resources:

* R-package [mfp](https://cran.r-project.org/web/packages/mfp/index.html)
* R-package [mfp2](https://cran.r-project.org/package=mfp2)
* MFP website with explanations, examples, software, links, etc.: [https://mfp.imbi.uni-freiburg.de/software](https://mfp.imbi.uni-freiburg.de/software)

### Augmented Backward Elimination

Augmented backward elimination combines significance or information based criteria with the change in estimate to either select the optimal model for prediction purposes or to serve as a tool to obtain a practically sound, highly interpretable model. More details can be found in [Dunkler et al. (2014)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0113677).

* R package: [abe](https://cran.r-project.org/web/packages/abe/index.html) Performs augmented backward elimination and checks 
the stability of the obtained model. 

### Tetris-plot

The Tetris-plot is a tool to visualize the instability of models obtained by variable selection.

* Github website with R package (development version): [https://gsk-biostatistics.github.io/tetrisplot](https://gsk-biostatistics.github.io/tetrisplot)


